apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
  - http:
      paths:
      - path: /mainservice
        pathType: Prefix
        backend:
          service:
            name: main-service
            port:
              number: 8082
