apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service-deployment
  labels:
    component: main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: main-service
  template:
    metadata:
      labels:
        component: main-service
      annotations:
        configmap-version: 1
    spec:
      containers:
        - name: main-service
          image: xmhai/main-service:2
          ports:
            - containerPort: 8082
          env:
            - name: service1.url
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: service1.url
            - name: external.api.url
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: external.api.url
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: ClusterIP
  selector:
    component: main-service
  ports:
    - port: 8082
      targetPort: 8082
      